<a href="https://colab.research.google.com/github/Shashank18ram/Data-Science/blob/main/FeatureScaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [6]:
df= pd.read_csv('/content/Diab.csv')
df.head()

,Pat_Id,Gender,OGTT,DBP,BMI,Age,Diabetic
0,101,Male,176,90,33.7,58,Yes
1,102,Male,150,66,34.7,42,No
2,103,Male,73,50,23.0,21,No
3,104,Female,187,68,37.7,41,Yes
4,105,Female,100,88,46.8,31,No


In [7]:
df.info(
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pat_Id    500 non-null    int64  
 1   Gender    500 non-null    object 
 2   OGTT      500 non-null    int64  
 3   DBP       500 non-null    int64  
 4   BMI       500 non-null    float64
 5   Age       500 non-null    int64  
 6   Diabetic  500 non-null    object 
dtypes: float64(1), int64(4), object(2)
memory usage: 27.5+ KB


In [8]:
dfScaler=df.copy()
dfScaler.drop(['Gender','Diabetic','Pat_Id'],axis=1,inplace=True)
dfScaler.head()

,OGTT,DBP,BMI,Age
0,176,90,33.7,58
1,150,66,34.7,42
2,73,50,23.0,21
3,187,68,37.7,41
4,100,88,46.8,31


In [9]:
dfScaler.columns

Index(['OGTT', 'DBP', 'BMI', 'Age'], dtype='object')

In [10]:
#StandardScaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

dfZScaling=scaler.fit_transform(dfScaler)
dfZScaling

array([[ 1.80631165,  1.51290352,  0.19122178,  2.13374943],
       [ 0.9576037 , -0.53756432,  0.33411654,  0.76967755],
       [-1.55587752, -1.90454288, -1.33775222, -1.02066678],
       ...,
       [-0.73981219, -1.05018128,  0.33411654, -0.93541229],
       [ 0.72910541,  1.17115888, -0.32319938, -0.8501578 ],
       [ 0.01096792,  0.4876696 , -0.65185734,  0.42865959]])

In [11]:
dfScaler.columns

Index(['OGTT', 'DBP', 'BMI', 'Age'], dtype='object')

In [12]:
from io import DEFAULT_BUFFER_SIZE
#convert this into np array
dfZScaling_df=pd.DataFrame(dfZScaling,columns=dfScaler.columns)
dfZScaling_df.head()

,OGTT,DBP,BMI,Age
0,1.806312,1.512904,0.191222,2.133749
1,0.957604,-0.537564,0.334117,0.769678
2,-1.555878,-1.904543,-1.337752,-1.020667
3,2.165380,-0.366692,0.762801,0.684423
4,-0.674527,1.342031,2.063143,-0.168122


In [13]:
#MINMAXScaling
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [14]:
df_MinMax=scaler.fit_transform(dfScaler)
df_MinMax

array([[0.85714286, 0.65217391, 0.31697342, 0.61666667],
       [0.68831169, 0.39130435, 0.33742331, 0.35      ],
       [0.18831169, 0.2173913 , 0.09815951, 0.        ],
       ...,
       [0.35064935, 0.32608696, 0.33742331, 0.01666667],
       [0.64285714, 0.60869565, 0.24335378, 0.03333333],
       [0.5       , 0.52173913, 0.19631902, 0.28333333]])

In [15]:
df_MinMaxx=pd.DataFrame(df_MinMax,columns=dfScaler.columns)
df_MinMaxx.head()

,OGTT,DBP,BMI,Age
0,0.857143,0.652174,0.316973,0.616667
1,0.688312,0.391304,0.337423,0.350000
2,0.188312,0.217391,0.098160,0.000000
3,0.928571,0.413043,0.398773,0.333333
4,0.363636,0.630435,0.584867,0.166667


In [16]:
#ROBUSTScaling
from sklearn.preprocessing import RobustScaler
scaler=RobustScaler()

In [17]:
df_RobustScaling=scaler.fit_transform(dfScaler)
df_RobustScaling

array([[ 1.45454545,  1.125     ,  0.19047619,  1.93333333],
       [ 0.82424242, -0.375     ,  0.30252101,  0.86666667],
       [-1.04242424, -1.375     , -1.00840336, -0.53333333],
       ...,
       [-0.43636364, -0.75      ,  0.30252101, -0.46666667],
       [ 0.65454545,  0.875     , -0.21288515, -0.4       ],
       [ 0.12121212,  0.375     , -0.47058824,  0.6       ]])

In [18]:
df_Robust=pd.DataFrame(df_RobustScaling,columns=dfScaler.columns)
df_Robust.head()

,OGTT,DBP,BMI,Age
0,1.454545,1.125,0.190476,1.933333
1,0.824242,-0.375,0.302521,0.866667
2,-1.042424,-1.375,-1.008403,-0.533333
3,1.721212,-0.250,0.638655,0.800000
4,-0.387879,1.000,1.658263,0.133333


Min-Max Scaling relies entirely on the absolute minimum and maximum values of a dataset to stretch or compress data between 0 and 1.

If an extreme outlier is present, it massively inflates the range, causing all normal data points to get tightly compressed into a tiny fraction close to 0.

In [21]:
dfEncoder=df.copy()

In [29]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse_output=False)
dfEncoder1=ohe.fit_transform(dfEncoder[['Gender']])
dfEncoder1

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.

 OneHotEncoder returns a hidden sparse matrix to save memory, which looks like a text description instead of actual data.

Setting sparse_output=False forces it to return a standard, readable NumPy array of 0s and 1s so you can easily view it and convert it into a Pandas DataFrame.

In [32]:
dfEncoder1=pd.DataFrame(dfEncoder1,columns=ohe.get_feature_names_out())
dfEncoder1.head()

,Gender_Female,Gender_Male
0,0.0,1.0
1,0.0,1.0
2,0.0,1.0
3,1.0,0.0
4,1.0,0.0


In [43]:
#label Encoding
dfLabel=df.copy()
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dfLabel['Diabetic']=le.fit_transform(dfLabel[['Diabetic']])
dfLabel.head()

,Pat_Id,Gender,OGTT,DBP,BMI,Age,Diabetic
0,101,Male,176,90,33.7,58,1
1,102,Male,150,66,34.7,42,0
2,103,Male,73,50,23.0,21,0
3,104,Female,187,68,37.7,41,1
4,105,Female,100,88,46.8,31,0


In [49]:
data ={
    'name': ['shashank','punith','ujwal'],
    'id':[101,103,106]
}

In [51]:
df=pd.DataFrame(data)
df

,name,id
0,shashank,101
1,punith,103
2,ujwal,106


In [52]:
dfoe=df.copy()
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
dfoe=oe.fit_transform(dfoe[['name','id']])
dfoe

array([[1., 0.],
       [0., 1.],
       [2., 2.]])

In [58]:
dfoe=pd.DataFrame(dfoe,columns=oe.feature_names_in_)
dfoe.head()

,name,id
0,1.0,0.0
1,0.0,1.0
2,2.0,2.0


In [ ]:
#Ordinal Encoder used for show the data in ascending order